/* Autogenerated by png2wx.pl on Thu Feb 21 12:36:45 2019 */
#ifndef SRC_IMAGES_HPP
#define SRC_IMAGES_HPP 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

namespace seabots_pi {
    void initialize_images(void);

    extern wxBitmap *_img_seabots;
}
#endif /* SRC_IMAGES_HPP */
